name: Create Vercel preview on pull request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snickerbockers/submodules-init@v4
      - uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./client
      - name: preview-url
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}